version: '3.8'

services:
  dbA:
    image: mysql:8.0
    container_name: dbA
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passA
      MYSQL_DATABASE: dbA
      MYSQL_USER: userA
      MYSQL_PASSWORD: passA
    ports:
      - "3306:3306"
    command:
      - --default-storage-engine=innodb
      - --binlog_format=ROW
      - --transaction-isolation=READ-COMMITTED
    volumes:
      - ./dbA_data:/var/lib/mysql

  dbB:
    image: postgres:13
    container_name: dbB
    restart: always
    environment:
      POSTGRES_USER: userB
      POSTGRES_PASSWORD: passB
      POSTGRES_DB: dbB
    ports:
      - "5432:5432"
    volumes:
      - ./dbB_data:/var/lib/postgresql/data
